### PR TITLE
Get org name using  env var instead of hitting the github api to get it

### PR DESCRIPTION
**Pull request by bronzdoc**
We are doing an unnecessary call to the github api just to get the name of the org. But we already have the name of the org available in `ENV["ORGANIZATION_LOGIN"]`

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by rdormer — APPROVED** [review]

**Comment by bronzdoc** [comment]
@ABizzinotto this is ready for QA

**Comment by ABizzinotto** [comment]
This PR is currently blocked by https://www.pivotaltracker.com/n/projects/2240452/stories/175742322

**Comment by ABizzinotto** [comment]
@bronzdoc @rdormer @arielj I wasn't able to deploy this PR to staging. Could you take a look?

**Comment by ABizzinotto** [comment]
@arielj @bronzdoc this is ready to merge!

**Pull request merged**
