### PR TITLE
Allow picking whick sub-projects to clone when cloning

### LINKED ISSUE #187: Select which sub-projects to clone when cloning a parent project
**Branch/Commit:**

Main branch

**Describe the feature:**

After merging this PR https://github.com/fastruby/points/pull/179, it will clone all the sub-projects of a given project when cloning it. It can be useful to have a list of checkboxes to select which specific sub-projects we want to clone.

**Problem:**

If we want to clone a project with a rails 2.3 to 6.0 upgrade for a new project for a rails 5.2 to 6.0 upgrade, we would have to clone the project and then delete all the extra sub-projects.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by arielj**
**Description:**

This PR adds the option to select which sub projects will be cloned when cloning a project.

One thing to notice: when cloning a project as a sub-project (picking a parent other than None), the option to clone sub-projects is disabled, since we don't allow nested sub-projects.

With sub-projects:
image

If picking a parent:
image

With no sub-projects:
image

Closes #187
___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
hey @FionaDL! can you review this when you have a chance? thanks!

**Comment by lubc** [comment]
@FionaDL 👀

**Review by bronzdoc — APPROVED** [review]

**Comment by bronzdoc** [comment]
@FionaDL please QA when you have a chance, thanks!

**Comment by bronzdoc** [comment]
@arielj this has a merge conflict, thanks :shipit:

**Comment by arielj** [comment]
> @arielj this has a merge conflict, thanks :shipit:

@bronzdoc fixed!

**Pull request merged**
