### PR TITLE
Move copy story url to clipboard button to the story dropdown menu

### LINKED ISSUE #218: Copy to clipboard button shows up in next line if story title using the complete first line
https://ombulabs.atlassian.net/browse/DT-248

**Branch/Commit:**

Main

**Expected behavior:**

The copy to clipboard button should show right at the end of the title.

**Actual behavior:**

The line wraps to a second line and the copy to clipboard button is in a weird position

**Steps to reproduce:**

Create a story with the name `Assigning ActiveStorage many association replaces elements instead of appending` for example.

**Screenshots and Videos**

image

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by mcelaney**
Closes #218

**Description:**

Depending on the length of a story description the "copy url to clipboard" icon could appear on the next line like so:

155324141-810f6ea9-eff6-4bea-8e19-ad8160fce859

Moved the button from being a hidden transition without a static location to the dropdown menu:

Screen Shot 2022-03-10 at 2 08 42 PM

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md).

Jira link https://ombulabs.atlassian.net/browse/DT-216

### CODE REVIEW

**Comment by mcelaney** [comment]
Question for our JavaScript-savvy friends - looking at [issue 218](https://github.com/fastruby/points/issues/218) on Points and I'm proposing moving the copy-to-clipboard link to the story dropdown. This works fine (see screenshot) if everyone is ok with the design change but for some reason I can't figure out the success-alert popup no longer shows up.  Looking at action_plan.js it seems like it should... not sure how I broke what I broke?

**Comment by FionaDL** [comment]
> 

Hey @mcelaney I imagine that the issue is not with the javascript, but with the css. The popup was happening within the container of the story before and the css surrounding it was based on it being in that location. I can see that when I inspect and click on the copy, it is momentarily changing the style in the code, but I think it won't work because the css doesn't make sense inside the dropdown menu. I could be wrong, but I believe that is what is happening.

**Comment by mcelaney** [comment]
@FionaDL That helped - thanks!

**Review by arielj — COMMENTED** [review]
hey @mcelaney the change looks good, one thing that looks like it's broken is the position of the `Copied to clipboard` popup, maybe it can popup on the right side of the row? something like `left: 100%`

**Comment by mcelaney** [comment]
@arielj 

> hey @mcelaney the change looks good, one thing that looks like it's broken is the position of the `Copied to clipboard` popup, maybe it can popup on the right side of the row? something like `left: 100%

That'll run it off the screen at most resolutions - how about `left: 80%` and have it touching the hotdog button that started it?

Screen Shot 2022-03-16 at 4 29 14 PM
`

**Comment by arielj** [comment]
> @arielj
> 
> > hey @mcelaney the change looks good, one thing that looks like it's broken is the position of the `Copied to clipboard` popup, maybe it can popup on the right side of the row? something like `left: 100%
> 
> That'll run it off the screen at most resolutions - how about `left: 80%` and have it touching the hotdog button that started it?
> 
> Screen Shot 2022-03-16 at 4 29 14 PM `

To prevent the message to overflow on smaller devices maybe a `right: 30px` is more consistent.

**Comment by rishijain** [comment]
hey @mcelaney can you please address the comments by Ariel here and let us know if no changes are needed, we will then further take this for QA? Thanks !

**Comment by rishijain** [comment]
Hey @mcelaney did you get a chance to look at it further?

**Comment by FionaDL** [comment]
@rishijain @hmdros QA looks good, merging! Nice Job!

**Pull request merged**
