### PR TITLE
WIP: Add form helper with better error message display

### PR DESCRIPTION
**Pull request by kaysiz**
**IMPORTANT: Please read the README before submitting pull requests for this project. Additionally, if your PR closes any open GitHub issues, make sure you include _Closes #XXXX_ in your comment or use the option on the PR's sidebar to add related issues to auto-close the issue that your PR fixes. **

**Description:**

Please include a summary of the change and which issue is fixed or which feature is introduced. If changes to the behavior are made, clearly describe what changes.
If changes to the UI are made, please include screenshots of the before and after.

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
Hi, @kaysiz! Just wondering what the status of this PR is. Thanks!

**Comment by kaysiz** [comment]
> Hi, @kaysiz! Just wondering what the status of this PR is. Thanks!

Removing the WIP this week.😃

**Comment by cleicar** [comment]
Hey @kaysiz are you still planning to work at this? What issue is it associated with? Can you update the description so we know what to expect? Thanks!

**Comment by bronzdoc** [comment]
ping @kaysiz

**Comment by kindoflew** [comment]
Closed as stale.

**Pull request closed without merging**
