### PR TITLE
fix create button behavior on estimating

### LINKED ISSUE #266: The Create button gets odd when estimating
While working on DT-372 I found this error.

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Expected behavior:**

Be able to create an estimation.

**Actual behavior:**

The button to save estimations gets odd.

error-points

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by DamonClark**
Closes #266 

Adds value attribute to the submit button in views.

image

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by JuanVqz** [comment]
Hey, @DamonClark thanks for taking the time to solve this issue, 
I ran the test suite twice but [still failed,](https://github.com/fastruby/points/actions/runs/3727519372/jobs/6543246785).
Could you please check why the tests are failing? 
If you have any questions, feel free to ask we can always help.

Happy new year :+1:

**Comment by DamonClark** [comment]
Hey @JuanVqz  looks like they are failing because the buttons isn't "Save Changes" but "Create" I'll commit the change to fix

**Comment by JuanVqz** [comment]
> Hey @JuanVqz looks like they are failing because the buttons isn't "Save Changes" but "Create" I'll commit the change to fix.
> 
> Happy new year !

Good call, Thanks for fixing them but now I'm concerned if "Save Changes" is better wording for this action, let me get a second point of view, sorry about that.

Hey, @fbuys | @arielj  what do you think about this?
In the beginning, I agreed with calling the button "Create" because is the way it shows up the first time when you click the "Add estimate" button but what if you are updating the estimations the next time, it makes me think "Save Changes" it's better wording.

**Comment by aisayo** [comment]
Hi, I think using `save changes` for this button makes the most sense since even when we are entering estimates for the first time, we are simply updating the points from 0 to an actual value. Makes more sense than using 'create'. What do you think @fbuys ?

**Comment by etagwerker** [comment]
@aisayo I agree with this: 

> Hi, I think using save changes for this button makes the most sense since even when we are entering estimates for the first time, we are simply updating the points from 0 to an actual value. Makes more sense than using 'create'.

**Comment by etagwerker** [comment]
@DamonClark Thanks for getting this started! I took some of your commits and continued this PR with #288 so I'm going to close this PR in favor of that one.

**Pull request closed without merging**
