### PR TITLE
Sort sub projects

### LINKED ISSUE #111: Add the ability to order sub-projects
**Branch/Commit:**

Main branch

**Describe the feature:**

As a user, I want to be able to re-order the sub-projects of a given project, so when I generate the complete action plan, the projects are in the expected order.

**Problem:**

Currently, the sub-projects of a given project are ordered in the creation order, if a new sub-project needs to be before a previous sub-project when generating the full action plan, that can't be done right now.

**Mockups:**

I imagine to use something like we do now with drag/drop of stories but for the list of subprojects, but I don't have a mock or a concrete idea.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by arielj**
**Description:**

This is a continuation of https://github.com/fastruby/points/pull/165

It includes:
- some refactor cleaning some things
- a drag/drop test for the added feature

Closes #111 
___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
hey @kaysiz! could you review this when you have a chance? thanks!

**Review by cleicar — APPROVED** [review]
Great addition to the project @arielj. Thanks!

**Comment by bronzdoc** [comment]
@kaysiz can you give this a review? thanks!

**Comment by lubc** [comment]
@kaysiz 👀

**Review by kaysiz — APPROVED** [review]
LGTM. I was able to create sub-projects and sort them by drag and drop 🚀

**Comment by lubc** [comment]
@arielj Once you fix the git conflicts we can merge this

**Comment by kindoflew** [comment]
hi @arielj! there are still some conflicts here blocking merge. thanks!

**Comment by arielj** [comment]
@lubc @kindoflew , done!

**Comment by kindoflew** [comment]
@ariel thanks! but CI is now failing 😅

**Comment by arielj** [comment]
> @ariel thanks! but CI is now failing sweat_smile

weird, it works locally, but I see where it might be failing (we have to do a `sleep` call and I don't like them), I'll se if I can workaround that in some way

**Comment by arielj** [comment]
@kindoflew seems to be fixed now! (I had to add more `sleep` calls to make this more stable), I can remove the upload of artifacts if needed, but I think it's ok to just leave that in the project since it doesn't hurt and can be useful

**Pull request merged**
