### PR TITLE
[Bugfix]: Code blocks are shown in non-monospace fonts

### LINKED ISSUE #191: Code blocks are shown in non-monospace fonts
**Branch/Commit:**

Main branch

**Expected behavior:**

Code blocks (created by indenting code with 4 spaces in a story description) should use a monospace font and should have horizontal scroll if the line doesn't fit.

**Actual behavior:**

Code blocks are displayed in a non-monospace font, making the code look like styled text instead of code. Also, code wraps into multiple lines.

Should be fairly easy to fix with some CSS.

**Steps to reproduce:**

Create any story and type some code using a 4-space indentation. Check the preview or save the story and open the show action.

**Screenshots and Videos**

image

Notice the table columns don't match. But With mono-space:

image

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### LINKED ISSUE #192: Long links break the new-story form design
**Branch/Commit:**

Main branch

**Expected behavior:**

The textarea with the description should have a minimum width so it's always readable.

**Actual behavior:**

If the description includes a super long link, it takes a lot of space, compressing the space for the textarea.

Some `min-width` CSS should fix this

**Steps to reproduce:**

Write a super long link in a description.

**Screenshots and Videos**

image

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by kindoflew**
Closes #191. Also, it might accidentally resolve #192. 

**Description:**

* adds a monospace font-family `scss` variable
* adds `overflow-x: scroll` to `code` elements
* modifies `grid-template-columns` of `.new_story` and `.edit_story` classes to use the `repeat` CSS function to avoid the code overflowing on long lines and ignore the `scroll` rule (context: https://css-tricks.com/equal-width-columns-in-css-grid-are-kinda-weird/)

**Screenshots:**
Screen Shot 2022-01-28 at 6 46 24 PM

Screen Shot 2022-01-28 at 6 47 20 PM

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
I'm not sure why CI is failing, it's passing locally for me? It looks like it's the test from #182 that added the `sleep` calls.

**Comment by kindoflew** [comment]
@kaysiz could you review this when you can? thanks! (also, ignore the failing tests for now, @arielj is going to investigate because it has to do with a previous PR).

**Comment by kindoflew** [comment]
hi again @kaysiz! just another reminder, thanks!

**Comment by arielj** [comment]
hey @kindoflew I pulled the main branch into this branch because I wanted to verify the flaky spec was gone, just so you know I'll have to pull before doing any change if needed

**Comment by arielj** [comment]
one thing to note, this PR will conflict with https://github.com/fastruby/points/pull/194 changing the grid columns if that PR is merged first

**Comment by kindoflew** [comment]
@ariel thanks for the heads up!

I actually pinged @fbuys in that PR to see which he preferred, and we can both just use the same one (although, I kind of prefer mine 😜 ).

**Review by kaysiz — APPROVED** [review]
LGTM

**Comment by fbuys** [comment]
Hey @kindoflew I only replied to https://github.com/fastruby/points/pull/194 just now. Sorry for the delay.

I'll quote my reply here for convenience:
```
 am a bit late. But it seems like making the lower bound 50% explicitly is clearer? Perhaps using 50% is also possible because we know it is only two columns. Using minmax(0, 1fr) is definitely the answer when you don't know how many columns you might have.

I am happy to use minmax(0, 1fr) but to me it seems like you need to have some understanding of the grid to know that it won't shrink all the way down to 0px.
```

**Comment by kindoflew** [comment]
@arielj should `build-rails-current` still be failing? the only thing I've changed since last time tests were run is one line of CSS.

**Comment by arielj** [comment]
@kindoflew re-runnig the test, I hate that drag_to tests, it's so unstable, if it's too flaky I'll continue debuggin to try to come up with a more stable solution if I can

**Review by bronzdoc — APPROVED** [review]

**Comment by arielj** [comment]
Sure, just checked and it looks good to me, code blocks are in mon-space font and things won't overflow

**Pull request merged**
