### PR TITLE
Add subprojects

### PR DESCRIPTION
**Pull request by rdormer**
**Description:**

This PR adds support for projects nested under other projects (sub-projects).  The nested project is a child of another project, and is displayed and edited accordingly.  See #16 for more  details.
Screen Shot 2021-02-03 at 1 05 36 PM

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by bronzdoc — APPROVED** [review]

**Comment by bronzdoc** [comment]
@arielj Can you QA this?

**Comment by bronzdoc** [comment]
Closes https://github.com/fastruby/points/issues/16

**Comment by arielj** [comment]
Doing the QA now, adding comments while testing it:

- This may be too subjective, but the `add subproject` is hard to find unless you know where to look for it, right now we need to go to edit a project to be able to add sub projects and it's not a screen you would think of going since the create form only has a title. Maybe it's more clear to display that option in the project's `show` page. Maybe next to the `edit or delete project` button?

- It's hard to navigate between the parent project and the subprojects, to go from parent to a child I have to go to the index and click the child, then to go back I have to go back again to the index. Maybe we can add a link to the parent project next to a child's project name in its `show` page, and add a list of subprojects right next to the parent's title (or maybe as a sidebar kind of thing?). We could have the `add subproject` action close to the list of subprojects too, like moving what we have on the edit page to the show page would make things faster to navigate

- When I try to create a subproject with no title, I have no feedback of the error (if I reload the page or move to another page I see the flash message), this is probably an issue with form_with doing an ajax request by default

- When editing a sub project, there's a double line, I guess moving the `hr` tag inside the `if @project.projects.count > 0` is enough:

image

@bronzdoc @rdormer here's the QA

**Comment by arielj** [comment]
@fastruby/black-bunny-brigade one more QA thing (most of the previous feedback is fixed 👍 )

When you go to `Add subproject`, clicking `Back` takes you to the index instead of the previous page. It should take you to the parent's show page again.

**Review by bronzdoc — APPROVED** [review]
This looks good @rdormer I think just one more comment to address from Ariel and we are good to go

**Pull request merged**
