### PR TITLE
Toggle the archive/unarchive text in the button

### LINKED ISSUE #153: Un/archive button always shows `Archive project` when page loads
**Branch/Commit:**

Main branch.

**Expected behavior:**

As a user, I want to see, in the project's show page, that a project is archived to un-archive it. The button should show the correct label and we could have a better visual indication if the project is archived: show an `(Archived)` label next to the project title for example.

**Actual behavior:**

After archiving a project, if the page is reloaded, the action to toggle if the project is archived or not says `Archive project` no matter the value.

**Steps to reproduce:**

1. Open a project's show page
2. Click `Archive Project`
3. Button should change to `Unarchive Project`
4. Refresh the page
5. Button says `Archive project` even though the project is already archived

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by cleicar**
**Description:**

This PR closes #153 and toggles the text in the archive/unarchive button in the projects page.

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Review by arielj — COMMENTED** [review]
Change looks fine, we should have a test for this just in case.

**Comment by lubc** [comment]
@cleicar hey, have you had a chance to look at Ariel's feedback? Thanks!

**Review by lubc — APPROVED** [review]

**Comment by lubc** [comment]
@fbuys Could you please QA this PR? Thank you!

**Review by fbuys — APPROVED** [review]
Test on main and on this branch it works as expected.
Screenshots show what I saw on main after archive and also now that it is fixed after refresh.
main after refresh
fixed after refresh

**Pull request merged**
