### PR TITLE
Rails 6.1 Upgrade

### PR DESCRIPTION
**Pull request by mateusdeap**
**Description:**

This PR will upgrade Points to Rails 6.1 with a possible update of the ruby version as well

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by arielj** [comment]
Hey @mateusdeap just a suggestion, add some label to this, maybe WIP? I started reviewing this and then I realized it's just the branch to hold all the changes for the upgrade

**Comment by kindoflew** [comment]
hi @mateusdeap! just wondering what the status of this is?

**Comment by mateusdeap** [comment]
@kindoflew I think we'd just need to do some manual testing. One thing I noticed is that I forgot to ask for a review 🤦 

On monday I'll ask to see who wants or can take this hahaha You can also take a crack at it. Familiarize yourself with points and all. Ask in slack about the reqs if you feel unsure, but, basically, if you can:

- Add a project
- Add a subproject
- Add stories
- Delete stories
- Bulk delete stories
- Estimate stories
- Edit stories

I think it's golden. Anything else, maybe, @etagwerker ?

**Comment by kindoflew** [comment]
I attempted to test this locally, but ran into an issue with logging in where I got this error when clicking "Sign in with GitHub":
```
Errno::ENOENT in CallbacksController#github
No such file or directory @ rb_sysopen - https://api.github.com/orgs/ombulabs/members
```
Where it seems to have a problem with this method:

```ruby
def organization_members
    @organization_members ||= begin
      # the next line is highlighted
      members_raw_response = open("https://api.github.com/orgs/#{ENV["ORGANIZATION_LOGIN"]}/members").read
      JSON.parse(members_raw_response)
    end
  end
```

If I change `open(...)` to `URI.open(...)` the error doesn't occur, but I still can't log in -- it tells me "This application is only available to members of ombulabs."

I'm not sure if this issue is me doing something wrong or if it's related to upgrading.

**Comment by etagwerker** [comment]
@kindoflew I think the issue is a "known gotcha": You need to make your membership to GitHub public so that you can sign in: 

Screen Shot 2021-09-24 at 8 07 57 PM
 
More here: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

**Comment by kindoflew** [comment]
@etagwerker Thanks!

In that case, I got it working, but only if I change that method to have `URI.open`.

After a little digging it seems that before Ruby 3.0, `open-uri` would override `Kernel#open` with its own version that also supported external URLs (Here's the commit that removed it: https://github.com/ruby/open-uri/commit/53862fa35887a34a8060aebf2241874240c2986a).

This PR bumps Ruby to 3.0.2, so I guess it's causing that error.

**Comment by etagwerker** [comment]
@kindoflew Thanks for looking into it! Could you please push that change to this branch?

**Comment by kindoflew** [comment]
@mateusdeap I manually tested the features you listed and everything looks good to me!

**Comment by etagwerker** [comment]
@kindoflew Great, thanks!

**Pull request merged**
