### PR TITLE
Fix error when editing two or more estimates

### LINKED ISSUE #114: Editing an estimate shows an error in the console and modal does not close
**Branch/Commit:**

Main branch.

**Expected behavior:**

After editing an estimate, the modal should close and the row should be updated.

**Actual behavior:**

There's an error in the browser console.

```
Uncaught SyntaxError: Identifier 'row' has already been declared
    at s (application-dbacd343b0c3f570848f9e9332727b8ae36cd7e34c221978d0f00a37b13b1f2e.js:1)
    at application-dbacd343b0c3f570848f9e9332727b8ae36cd7e34c221978d0f00a37b13b1f2e.js:1
    at XMLHttpRequest.i.onreadystatechange (application-dbacd343b0c3f570848f9e9332727b8ae36cd7e34c221978d0f00a37b13b1f2e.js:1)
```

**Steps to reproduce:**

Try editing 2 estimates without refreshing the page, the JS response tries to declare `const row =` and it fails to do so the second time.

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by arielj**
**Description:**

This PR fixes an issue where the js response when editing an estimate would do something like `let row = ...` in the global scope. Then, the second time an edit is made, this would fail trying to re-define the `row` variable.

I update if to not polute the global scope wrapping the response in a function.

Closes #114 
___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Review by lubc — APPROVED** [review]

**Comment by lubc** [comment]
@mateusdeap hey, could you QA this PR? Thanks!

**Comment by mateusdeap** [comment]
@lubc How do I redeploy the app? Only in heroku?

**Comment by lubc** [comment]
> @lubc How do I redeploy the app? Only in heroku?

@mateusdeap You can login into Heroku, go to Points (https://dashboard.heroku.com/pipelines/326aacc6-56b7-46dd-829d-f14e5d62e9ba), and deploy this branch to staging or to Review Apps

**Comment by mateusdeap** [comment]
Found a possible bug:
image

I don't know if it's related to @arielj's changes, but if I put a value in the worst case scenario that is lower than the best case scenario, the button's text disappears. I saw no errors in the console.

**Comment by arielj** [comment]
> Found a possible bug: image
> 
> I don't know if it's related to @arielj's changes, but if I put a value in the worst case scenario that is lower than the best case scenario, the button's text disappears. I saw no errors in the console.

not related to this PR, there's a bug report for that one https://github.com/fastruby/points/issues/115

**Review by bronzdoc — APPROVED** [review]

**Comment by bronzdoc** [comment]
@arielj can you fix the merge conflict? thanks

**Review by mateusdeap — APPROVED** [review]

**Comment by arielj** [comment]
@bronzdoc done!

**Pull request merged**
