### PR TITLE
Updates Modal's event loading so that it always fires

### LINKED ISSUE #65: Add estimates does not always display modal to perform the action 😞
**Before we start...:**

- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Branch/Commit:**

main branch

**Expected behavior:**

Clicking add estimate should always display a modal.

**Actual behavior:**

Sometimes clicking add estimate does not display a modal. 

**Steps to reproduce:**

It's hard to find it, but I've experimented it in both Safari and Chrome

1. Step 1: Load a new project page
2. Step 2: Click add estimate 

**Screenshots and Videos**

I will share this privately as it has sensitive details in the video I captured. 

**Logs**

Unfortunately there are no details in the JS console... 😢 

**I will abide by the [code of conduct](CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by torresga**
**Description:**

Closes #65. 

From what I’ve read from the Turbolinks documentation, we should be using the `turbo links:load` event in place of `DOMContentLoaded` so that the JavaScript is executed on every page change. I think the default behavior with Turbolinks is that `DOMContentLoaded` fires only in response to the initial page load, not after any subsequent page changes, so that’s why the modal only pops up intermittently. (For reference: https://github.com/turbolinks/turbolinks#installing-javascript-behavior)

I ended up testing this manually (going from page to page, pressing the ‘Add Estimate’ button to see if it appears.) If anyone can point me towards some ideas towards testing this through a spec, I would be happy to hear it. 

I will abide by the [code of conduct](https://github.com/fastruby/points/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by bronzdoc** [comment]
Thanks for this @torresga! I was trying to QA it now but it seems something is broken with review apps, I will give it a look
Screen Shot 2021-08-16 at 4 30 27 PM

**Review by arielj — APPROVED** [review]
Looks good to me, I'm deploying this to staging instead of the review apps since that's not working (check https://github.com/fastruby/points/issues/48)

**Comment by arielj** [comment]
https://staging.points.ombulabs.com/projects

**Comment by arielj** [comment]
> I ended up testing this manually (going from page to page, pressing the ‘Add Estimate’ button to see if it appears.) If anyone can point me towards some ideas towards testing this through a spec, I would be happy to hear it.

@torresga if you want to add an automated test for this, you can probably do the same steps you did for the manual testing with a system spec. Something like (pseudocode):

```
visit("/")
click some_project
click add_estimate
assert that the modal is visible
close the modal
click the title (to go back to the dashboard)
click some_project
click add_estimate
assert that the modal is visible
```

Doing those steps locally before and after the fix was consistent for me to test it, so the test should work (you can remove the fix when adding the test just to be sure fix is fixing the test)

**Review by cleicar — APPROVED** [review]
This looks great @torresga. Thank you!

**Pull request merged**
