### PR TITLE
Collapse row actions in a 'more' button and restyle

### LINKED ISSUE #140: Collapse stories actions in the rows
**Branch/Commit:**

Main branch

**Describe the feature:**

The actions for each story in the project's show page should use less space so there's more room for the story title and to make it look less bloated

**Problem:**

This is what the page looks like now (before adding the `Move to` button from another issue, when that gets merges this will be even worse)
image

And the layout starts looking really bad with not that small screens already
image

**Mockups:**

We have 2 options:
- we can replace buttons with icons (trash can to delete, pencil to edit, a copy icon for the clone, etc)
- we can only show the most used buttons (Edit and Add/Edit Estimate?) and group the rest of the actions under a `...` button to show the rest of the options

I personally prefer the idea of having icons, I think it looks cleaner and we don't need an extra click on a `...` icon to show more options (which makes it hard to discover new actions for example)

If we go with icons, we are already uses font-awesome so we could have:
- Clone https://fontawesome.com/v4.7/icon/files-o
- Delete https://fontawesome.com/v4.7/icon/trash-o
- Edit https://fontawesome.com/v4.7/icon/pencil-square-o
- Add/Edit Estimate https://fontawesome.com/v4.7/icon/signal maybe?
- Move to https://fontawesome.com/v4.7/icon/share-square-o

**I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/CODE_OF_CONDUCT.md)**

### PR DESCRIPTION
**Pull request by arielj**
**Description:**

This PR is a restyle of the row's actions in the project's show page. The current group of actions is too big with many option options that are not used too often (like clone, destroy, move to). I also changed the white over green buttons to the less blinding black over yellow colors.

After checking with nathalie, we decided the best UX is to only show the button with text for the main action (add/edit estimates) and group the rest of the actions in a dropdown, instead of showing all the options as buttons as described in the linked issue.

There are other suggestions to improve the colors and hovers style of buttons but I'll add some issues to address those suggestions.

image

`more actions` dropdown
image

`move to` dropdown
image

Closes #140 

___

I will abide by the [code of conduct](https://github.com/fastruby/points/blob/main/pull_request_template.md).

### CODE REVIEW

**Comment by kindoflew** [comment]
This looks good to me! I was following along in Slack, and I like this dropdown style better as well!

My only thought is to maybe move the nested `move to` dropdown off to the side, instead of on top of the other dropdown? But that might be nitpicking 🤔 .

Hi @mateusdeap! Could you QA this when you have a chance? Thanks!

**Review by kindoflew — APPROVED** [review]

**Comment by arielj** [comment]
> My only thought is to maybe move the nested `move to` dropdown off to the side, instead of on top of the other dropdown? But that might be nitpicking thinking .

I changed it :+1:

image

**Comment by lubc** [comment]
@arielj could you please fix the git conflict? thanks!

**Comment by lubc** [comment]
@mateusdeap hey, when you have some time please do the QA of it. Thank you!

**Comment by mateusdeap** [comment]
So I noticed something and I'm not sure if it's a pre existing bug or introduced in this change.

When I create a story, the Add Estimate button is yellow
image

Once I add it, it becomes Edit Estimate and it's green
image

If I open the dropdown and edit the story
image

Once I'm done, it's yellow again.
image

Is this expected?

**Comment by mateusdeap** [comment]
Otherwise, this looks good to me. @arielj Just want some feedback on my previous comment before approving

**Comment by arielj** [comment]
@mateusdeap I pushed a fix for the button's color after adding an estimate, it shouldn't turn green now

**Review by mateusdeap — APPROVED** [review]

**Comment by mateusdeap** [comment]
LGTM

**Review by cleicar — APPROVED** [review]
Looks great! 🚀

**Pull request merged**
